// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/xraph/forgeui/components/button"
	"github.com/xraph/forgeui/components/card"
	"github.com/xraph/forgeui/components/input"
	"github.com/xraph/forgeui/icons"
)

// FlagCreateData holds data for the flag create form.
type FlagCreateData struct {
	Error string
	AppID string
}

func FlagCreatePage(data FlagCreateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\"><!-- Back Button -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = icons.ChevronLeft(icons.WithSize(16)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " Back to Flags")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = button.Button(button.Props{
			Variant: button.VariantGhost,
			Size:    button.SizeSm,
			Attributes: templ.Attributes{
				"hx-get":      "../flags",
				"hx-target":   "#content",
				"hx-swap":     "innerHTML",
				"hx-push-url": "true",
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div><h1 class=\"text-3xl font-bold tracking-tight\">Create Feature Flag</h1><p class=\"text-muted-foreground mt-1\">Define a new feature flag with type and default value.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Error != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"bg-destructive/10 text-destructive rounded-sm p-4 text-sm\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Error)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard/pages/flag_create.templ`, Line: 40, Col: 16}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<form class=\"space-y-6 p-6\" hx-post=\".\" hx-target=\"#content\" hx-swap=\"innerHTML\" onsubmit=\"if(!prepareFlagValue(this)){event.preventDefault();return false;}\"><input type=\"hidden\" name=\"action\" value=\"create_flag\"><div class=\"grid grid-cols-1 sm:grid-cols-2 gap-6\"><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"key\">Key</label>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = input.Input(input.Props{
					Type:        input.TypeText,
					Name:        "key",
					Placeholder: "e.g. enable_dark_mode",
					Attributes: templ.Attributes{
						"required": "true",
						"id":       "key",
					},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"app_id\">App ID</label>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = input.Input(input.Props{
					Type:        input.TypeText,
					Name:        "app_id",
					Placeholder: "e.g. myapp",
					Attributes: templ.Attributes{
						"id":    "app_id",
						"value": data.AppID,
					},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"flag_type\">Type</label> <select id=\"flag_type\" name=\"flag_type\" onchange=\"toggleFlagValueEditor()\" class=\"flex h-10 w-full rounded-sm border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2\"><option value=\"bool\">bool</option> <option value=\"string\">string</option> <option value=\"int\">int</option> <option value=\"float\">float</option> <option value=\"json\">json</option> <option value=\"yaml\">yaml</option></select></div><!-- Simple value input (bool, string, int, float) --><div id=\"flag-simple-value\" class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"default_value\">Default Value</label>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = input.Input(input.Props{
					Type:        input.TypeText,
					Name:        "default_value",
					Placeholder: "e.g. true, hello, 42",
					Attributes: templ.Attributes{
						"required": "true",
						"id":       "default_value",
					},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><!-- Code editor for json / yaml --><div id=\"flag-code-value\" class=\"space-y-2 hidden\"><div class=\"flex items-center justify-between\"><label class=\"text-sm font-medium\" for=\"default_value_code\">Default Value</label> <span id=\"flag-code-lang\" class=\"text-xs text-muted-foreground font-mono uppercase\"></span></div><textarea id=\"default_value_code\" name=\"default_value_code\" class=\"flex min-h-[200px] w-full rounded-sm border border-input bg-muted/30 px-4 py-3 font-mono text-sm leading-relaxed ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2\" oninput=\"debouncedFlagValidate()\" onblur=\"validateFlagCode()\" spellcheck=\"false\"></textarea><p id=\"flag-code-error\" class=\"text-destructive text-xs mt-1 hidden\"></p><p id=\"flag-code-valid\" class=\"text-emerald-600 dark:text-emerald-400 text-xs mt-1 hidden\"></p></div><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"description\">Description</label> <textarea id=\"description\" name=\"description\" class=\"flex min-h-[80px] w-full rounded-sm border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2\" placeholder=\"Describe what this flag controls...\"></textarea></div><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"tags\">Tags (comma-separated)</label>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = input.Input(input.Props{
					Type:        input.TypeText,
					Name:        "tags",
					Placeholder: "e.g. frontend, experiment, beta",
					Attributes: templ.Attributes{
						"id": "tags",
					},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div><div class=\"flex items-center gap-2\"><input type=\"checkbox\" id=\"enabled\" name=\"enabled\" value=\"true\" checked class=\"h-4 w-4 rounded-sm border border-input\"> <label class=\"text-sm font-medium\" for=\"enabled\">Enabled</label></div><div class=\"flex justify-end gap-3\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "Cancel")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = button.Button(button.Props{
					Variant: button.VariantOutline,
					Attributes: templ.Attributes{
						"hx-get":      "../flags",
						"hx-target":   "#content",
						"hx-swap":     "innerHTML",
						"hx-push-url": "true",
						"type":        "button",
					},
				}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = icons.Flag(icons.WithSize(16)).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " Create Flag")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = button.Button(button.Props{
					Variant: button.VariantDefault,
					Attributes: templ.Attributes{
						"type": "submit",
					},
				}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></form>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = card.Content().Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = card.Card(card.Props{Class: "rounded-sm"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div><script src=\"https://cdn.jsdelivr.net/npm/js-yaml@4/dist/js-yaml.min.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = flagCreateScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// flagCreateScript toggles between simple input and code editor based on flag type.
func flagCreateScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_flagCreateScript_9a3c`,
		Function: `function __templ_flagCreateScript_9a3c(){var _flagValidateTimer = null;

	window.debouncedFlagValidate = function() {
		clearTimeout(_flagValidateTimer);
		_flagValidateTimer = setTimeout(validateFlagCode, 400);
	};

	window.validateFlagCode = function() {
		var ft = document.getElementById('flag_type').value;
		var codeInput = document.getElementById('default_value_code');
		var errorDiv = document.getElementById('flag-code-error');
		var validDiv = document.getElementById('flag-code-valid');
		var val = codeInput.value.trim();

		// Reset state.
		errorDiv.classList.add('hidden');
		errorDiv.textContent = '';
		validDiv.classList.add('hidden');
		validDiv.textContent = '';
		codeInput.classList.remove('!border-destructive', '!border-emerald-500');

		if (!val) {
			return true;
		}

		var error = null;

		if (ft === 'json') {
			try {
				JSON.parse(val);
			} catch (e) {
				error = e.message;
			}
		} else if (ft === 'yaml') {
			if (typeof jsyaml !== 'undefined') {
				try {
					jsyaml.load(val);
				} catch (e) {
					error = e.reason || e.message;
				}
			}
		}

		if (error) {
			errorDiv.textContent = ft.toUpperCase() + ' syntax error: ' + error;
			errorDiv.classList.remove('hidden');
			codeInput.classList.add('!border-destructive');
			return false;
		}

		validDiv.textContent = 'Valid ' + ft.toUpperCase();
		validDiv.classList.remove('hidden');
		codeInput.classList.add('!border-emerald-500');
		return true;
	};

	window.toggleFlagValueEditor = function() {
		var ft = document.getElementById('flag_type').value;
		var simple = document.getElementById('flag-simple-value');
		var code = document.getElementById('flag-code-value');
		var langLabel = document.getElementById('flag-code-lang');
		var simpleInput = document.getElementById('default_value');
		var codeInput = document.getElementById('default_value_code');
		var errorDiv = document.getElementById('flag-code-error');
		var validDiv = document.getElementById('flag-code-valid');

		if (ft === 'json' || ft === 'yaml') {
			simple.classList.add('hidden');
			code.classList.remove('hidden');
			simpleInput.removeAttribute('required');
			langLabel.textContent = ft.toUpperCase();

			// Reset validation state on type switch.
			errorDiv.classList.add('hidden');
			validDiv.classList.add('hidden');
			codeInput.classList.remove('!border-destructive', '!border-emerald-500');

			if (ft === 'json') {
				codeInput.placeholder = '{\n  "key": "value"\n}';
			} else {
				codeInput.placeholder = 'key: value\nnested:\n  field: true';
			}

			// Re-validate existing content for the new type.
			if (codeInput.value.trim()) {
				validateFlagCode();
			}
		} else {
			simple.classList.remove('hidden');
			code.classList.add('hidden');
			simpleInput.setAttribute('required', 'true');
		}
	};

	// Before submit, validate and copy code editor value into the simple
	// value field so the server always reads from "default_value".
	window.prepareFlagValue = function(form) {
		var ft = document.getElementById('flag_type').value;
		if (ft === 'json' || ft === 'yaml') {
			if (!validateFlagCode()) {
				return false;
			}

			var codeInput = document.getElementById('default_value_code');
			var simpleInput = document.getElementById('default_value');
			simpleInput.value = codeInput.value;
			simpleInput.removeAttribute('required');
		}

		return true;
	};

	// Initialize on load.
	toggleFlagValueEditor();
}`,
		Call:       templ.SafeScript(`__templ_flagCreateScript_9a3c`),
		CallInline: templ.SafeScriptInline(`__templ_flagCreateScript_9a3c`),
	}
}

var _ = templruntime.GeneratedTemplate
